# Moving Average Family

In a moving average (MA) process, the current value depends linearly on the mean of the series, the current error term, and past error terms. The moving average model is denoted as MA(q), where q is the order.

**Table of contents**<a id='toc0_'></a>    
- [Preprocessing](#toc1_)    
  - [Import + setup](#toc1_1_)    
  - [Upload](#toc1_2_)    
  - [Make time serie stationary](#toc1_3_)    
  - [Plotting time series + ACF + PACF](#toc1_4_)    
  - [First main](#toc1_5_)    
  - [Check autocorrelation](#toc1_6_)    
- [Forecast](#toc2_)    
  - [Rolling forecast](#toc2_1_)    

<!-- vscode-jupyter-toc-config
	numbering=false
	anchor=true
	flat=false
	minLevel=1
	maxLevel=6
	/vscode-jupyter-toc-config -->
<!-- THIS CELL WILL BE REPLACED ON TOC UPDATE. DO NOT WRITE YOUR TEXT IN THIS CELL -->

# <a id='toc1_'></a>[Preprocessing](#toc0_)

## <a id='toc1_1_'></a>[Import + setup](#toc0_)

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
from src.config import set_seeds
import src.pipeline as pipe
import src.models as mod
import src.evaluation as eval
import src.reporting as rep
import src.visualization as visual
import pandas as pd
import time
import warnings
warnings.filterwarnings("ignore", message="'force_all_finite' was renamed")
warnings.filterwarnings("ignore", message="Non-stationary starting moving average parameters")
warnings.filterwarnings("ignore", category=UserWarning, module="statsmodels")

In [3]:
set_seeds()

Random seeds set to 42. Deterministic operations enabled.

## <a id='toc1_2_'></a>[Upload](#toc0_)

In [4]:
df = pipe.load_data()
display(df.head())

Dropped 9 unusable indicators.
Dataset loaded: 65 years (from 1960 to 2024), 27 variables.

,population_percent,population_growth,population_abs,employment_tot,employment_male,employment_female,forestarea_percent,forestarea_abs,agriland_percent,agriland_abs,...,fertilizer_percent,livestock_production_index,food_production_index,crop_production_index,cereal_production,cerealyield_abs,valueadded_percent,valueadded_dollars,exports_percent,imports_percent
1960-01-01,40.639,NaN,20400656.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1961-01-01,40.144,-0.557139,20287312.0,NaN,NaN,NaN,NaN,NaN,70.324028,206830.0,...,72.707716,70.91,85.93,93.68,13933400.0,2181.5,NaN,NaN,NaN,NaN
1962-01-01,39.645,-0.574190,20171158.0,NaN,NaN,NaN,NaN,NaN,70.218626,206520.0,...,70.071359,72.59,86.90,94.43,14433210.0,2225.3,NaN,NaN,2.563660,16.566057
1963-01-01,39.147,-0.534554,20063620.0,NaN,NaN,NaN,NaN,NaN,69.735813,205100.0,...,63.883735,65.95,86.37,97.19,13324660.0,2115.2,NaN,NaN,2.651714,14.571604
1964-01-01,38.650,-0.455075,19972523.0,NaN,NaN,NaN,NaN,NaN,69.572609,204620.0,...,64.593354,69.57,90.28,101.31,14007520.0,2243.0,NaN,NaN,2.792923,15.115329

## Sanity Check

In [5]:
visual.plot_sanity_check(df)

Check plot saved: C:\Users\oldan\Desktop\RuralDevelopment\progetto-tirocinio\results\plots\00_DIFFCHECK\DIFFCHECK_population_percent.png
Check plot saved: C:\Users\oldan\Desktop\RuralDevelopment\progetto-tirocinio\results\plots\00_DIFFCHECK\DIFFCHECK_population_growth.png
Check plot saved: C:\Users\oldan\Desktop\RuralDevelopment\progetto-tirocinio\results\plots\00_DIFFCHECK\DIFFCHECK_population_abs.png
Check plot saved: C:\Users\oldan\Desktop\RuralDevelopment\progetto-tirocinio\results\plots\00_DIFFCHECK\DIFFCHECK_employment_tot.png
Check plot saved: C:\Users\oldan\Desktop\RuralDevelopment\progetto-tirocinio\results\plots\00_DIFFCHECK\DIFFCHECK_employment_male.png
Check plot saved: C:\Users\oldan\Desktop\RuralDevelopment\progetto-tirocinio\results\plots\00_DIFFCHECK\DIFFCHECK_employment_female.png
Check plot saved: C:\Users\oldan\Desktop\RuralDevelopment\progetto-tirocinio\results\plots\00_DIFFCHECK\DIFFCHECK_forestarea_percent.png
Check plot saved: C:\Users\oldan\Desktop\RuralDevelopment\progetto-tirocinio\results\plots\00_DIFFCHECK\DIFFCHECK_forestarea_abs.png
Check plot saved: C:\Users\oldan\Desktop\RuralDevelopment\progetto-tirocinio\results\plots\00_DIFFCHECK\DIFFCHECK_agriland_percent.png
Check plot saved: C:\Users\oldan\Desktop\RuralDevelopment\progetto-tirocinio\results\plots\00_DIFFCHECK\DIFFCHECK_agriland_abs.png
Check plot saved: C:\Users\oldan\Desktop\RuralDevelopment\progetto-tirocinio\results\plots\00_DIFFCHECK\DIFFCHECK_arableland_percent.png
Check plot saved: C:\Users\oldan\Desktop\RuralDevelopment\progetto-tirocinio\results\plots\00_DIFFCHECK\DIFFCHECK_arableland_person.png
Check plot saved: C:\Users\oldan\Desktop\RuralDevelopment\progetto-tirocinio\results\plots\00_DIFFCHECK\DIFFCHECK_arableland_abs.png
Check plot saved: C:\Users\oldan\Desktop\RuralDevelopment\progetto-tirocinio\results\plots\00_DIFFCHECK\DIFFCHECK_cerealland_abs.png
Check plot saved: C:\Users\oldan\Desktop\RuralDevelopment\progetto-tirocinio\results\plots\00_DIFFCHECK\DIFFCHECK_cropland_percent.png
Check plot saved: C:\Users\oldan\Desktop\RuralDevelopment\progetto-tirocinio\results\plots\00_DIFFCHECK\DIFFCHECK_withdrawals_percent.png
Check plot saved: C:\Users\oldan\Desktop\RuralDevelopment\progetto-tirocinio\results\plots\00_DIFFCHECK\DIFFCHECK_fertilizer_abs.png
Check plot saved: C:\Users\oldan\Desktop\RuralDevelopment\progetto-tirocinio\results\plots\00_DIFFCHECK\DIFFCHECK_fertilizer_percent.png
Check plot saved: C:\Users\oldan\Desktop\RuralDevelopment\progetto-tirocinio\results\plots\00_DIFFCHECK\DIFFCHECK_livestock_production_index.png
Check plot saved: C:\Users\oldan\Desktop\RuralDevelopment\progetto-tirocinio\results\plots\00_DIFFCHECK\DIFFCHECK_food_production_index.png
Check plot saved: C:\Users\oldan\Desktop\RuralDevelopment\progetto-tirocinio\results\plots\00_DIFFCHECK\DIFFCHECK_crop_production_index.png
Check plot saved: C:\Users\oldan\Desktop\RuralDevelopment\progetto-tirocinio\results\plots\00_DIFFCHECK\DIFFCHECK_cereal_production.png
Check plot saved: C:\Users\oldan\Desktop\RuralDevelopment\progetto-tirocinio\results\plots\00_DIFFCHECK\DIFFCHECK_cerealyield_abs.png
Check plot saved: C:\Users\oldan\Desktop\RuralDevelopment\progetto-tirocinio\results\plots\00_DIFFCHECK\DIFFCHECK_valueadded_percent.png
Check plot saved: C:\Users\oldan\Desktop\RuralDevelopment\progetto-tirocinio\results\plots\00_DIFFCHECK\DIFFCHECK_valueadded_dollars.png
Check plot saved: C:\Users\oldan\Desktop\RuralDevelopment\progetto-tirocinio\results\plots\00_DIFFCHECK\DIFFCHECK_exports_percent.png
Check plot saved: C:\Users\oldan\Desktop\RuralDevelopment\progetto-tirocinio\results\plots\00_DIFFCHECK\DIFFCHECK_imports_percent.png

## Finding correct Integration Order for each indicator
Searching d on both the train set and the full serie to avoid data leakage. <br>
Saving all necessary information in master configuration (excel)

In [5]:
config_data = []

print("--- Integration Order and Initialization Parameters Configuration ---")
# i search for the optimal d differentiations on the train set and on the full series 
# to apply as parameter d of the ARIMA order in the following steps
for col in df.columns:
    if df[col].dropna().empty: continue
    full_series = df[col].dropna()
    
    train, test = pipe.split_train_test(df, col)
    train_series = train['Value'].dropna()
    
    print(f"\nProcessing {col}...")
    
    # VALIDATION PHASE (Train Set)
    # to avoid data leakage I calculate the integration order on the train serie
    print("Validation phase")
    d_train = pipe.find_integration_order(train_series, max_d=2)
    # to reconstruct the predictions on the test set, we save train set's last value
    # real_pred_t1 = last_train_val + pred_diff_t1
    last_val_train = train_series.iloc[-1]
    
    # FUTURE PHASE (Full Set)
    # I calculate the integration order on the full history to forecast values up until 2030
    print("Future phase")
    d_full = pipe.find_integration_order(full_series, max_d=1)
    # to reconstruct the predictions on future, we save full history's last value
    last_val_full = full_series.iloc[-1]
    
    config_data.append({
        'Indicator': col,
        
        # VALIDATION (Test Set)
        'd_train': d_train,
        'last_val_train': last_val_train,
        'train_end_year': train_series.index.max().year,
        
        # FUTURE (2030)
        'd_full': d_full,
        'last_val_full': last_val_full,
        'full_end_year': full_series.index.max().year
    })

config_df = pd.DataFrame(config_data)
config_df.set_index('Indicator', inplace=True)

rep.save_master_config(config_df)

--- Integration Order and Initialization Parameters Configuration ---

Processing population_percent...
Validation phase
  StdDev (d=0): 2.3230
  StdDev (d=1): 0.1811
  StdDev (d=2): 0.0386
  -> Optimal d (Variance Rule): 2
  -> Optimal d (KPSS Test):     2
  => FINAL DECISION: d=2
Future phase
  StdDev (d=0): 2.8435
  StdDev (d=1): 0.1685
  StdDev (d=2): 0.0388
  -> Optimal d (Variance Rule): 2
  -> Optimal d (KPSS Test):     1
  => FINAL DECISION: d=1

Processing population_growth...
Validation phase
  StdDev (d=0): 0.3088
  StdDev (d=1): 0.1528
  StdDev (d=2): 0.1821
  -> Optimal d (Variance Rule): 1
  -> Optimal d (KPSS Test):     1
  => FINAL DECISION: d=1
Future phase
  StdDev (d=0): 0.5099
  StdDev (d=1): 0.2100
  StdDev (d=2): 0.2974
  -> Optimal d (Variance Rule): 1
  -> Optimal d (KPSS Test):     0
  => FINAL DECISION: d=1

Processing population_abs...
Validation phase
  StdDev (d=0): 462571.8079
  StdDev (d=1): 59917.6575
  StdDev (d=2): 28938.4882
  -> Optimal d (Variance Rule): 2
  -> Optimal d (KPSS Test):     2
  => FINAL DECISION: d=2
Future phase
  StdDev (d=0): 790041.9773
  StdDev (d=1): 91183.0453
  StdDev (d=2): 38549.4851
  -> Optimal d (Variance Rule): 2
  -> Optimal d (KPSS Test):     1
  => FINAL DECISION: d=1

Processing employment_tot...
Validation phase
  StdDev (d=0): 1.4461
  StdDev (d=1): 0.2473
  StdDev (d=2): 0.2857
  -> Optimal d (Variance Rule): 1
  -> Optimal d (KPSS Test):     2
  => FINAL DECISION: d=1
Future phase
  StdDev (d=0): 1.3698
  StdDev (d=1): 0.2350
  StdDev (d=2): 0.2640
  -> Optimal d (Variance Rule): 1
  -> Optimal d (KPSS Test):     1
  => FINAL DECISION: d=1

Processing employment_male...
Validation phase
  StdDev (d=0): 1.1301
  StdDev (d=1): 0.2309
  StdDev (d=2): 0.2493
  -> Optimal d (Variance Rule): 1
  -> Optimal d (KPSS Test):     2
  => FINAL DECISION: d=1
Future phase
  StdDev (d=0): 1.0342
  StdDev (d=1): 0.2264
  StdDev (d=2): 0.2467
  -> Optimal d (Variance Rule): 1
  -> Optimal d (KPSS Test):     1
  => FINAL DECISION: d=1

Processing employment_female...
Validation phase
  StdDev (d=0): 1.9243
  StdDev (d=1): 0.3251
  StdDev (d=2): 0.4148
  -> Optimal d (Variance Rule): 1
  -> Optimal d (KPSS Test):     2
  => FINAL DECISION: d=1
Future phase
  StdDev (d=0): 1.8737
  StdDev (d=1): 0.3017
  StdDev (d=2): 0.3700
  -> Optimal d (Variance Rule): 1
  -> Optimal d (KPSS Test):     1
  => FINAL DECISION: d=1

Processing forestarea_percent...
Validation phase
  StdDev (d=0): 1.7214
  StdDev (d=1): 0.0392
  StdDev (d=2): 0.0406
  -> Optimal d (Variance Rule): 1
  -> Optimal d (KPSS Test):     2
  => FINAL DECISION: d=1
Future phase
  StdDev (d=0): 2.0717
  StdDev (d=1): 0.0390
  StdDev (d=2): 0.0356
  -> Optimal d (Variance Rule): 2
  -> Optimal d (KPSS Test):     1
  => FINAL DECISION: d=1

Processing forestarea_abs...
Validation phase
  StdDev (d=0): 5272.0295
  StdDev (d=1): 92.1938
  StdDev (d=2): 34.0800
  -> Optimal d (Variance Rule): 2
  -> Optimal d (KPSS Test):     2
  => FINAL DECISION: d=2
Future phase
  StdDev (d=0): 6291.2056
  StdDev (d=1): 101.3946
  StdDev (d=2): 30.1452
  -> Optimal d (Variance Rule): 2
  -> Optimal d (KPSS Test):     1
  => FINAL DECISION: d=1

Processing agriland_percent...
Validation phase
  StdDev (d=0): 6.8328
  StdDev (d=1): 1.3549
  StdDev (d=2): 1.9480
  -> Optimal d (Variance Rule): 1
  -> Optimal d (KPSS Test):     1
  => FINAL DECISION: d=1
Future phase
  StdDev (d=0): 8.3430
  StdDev (d=1): 1.3522
  StdDev (d=2): 2.0141
  -> Optimal d (Variance Rule): 1
  -> Optimal d (KPSS Test):     1
  => FINAL DECISION: d=1

Processing agriland_abs...
Validation phase
  StdDev (d=0): 19563.0023
  StdDev (d=1): 3995.6016
  StdDev (d=2): 5661.1784
  -> Optimal d (Variance Rule): 1
  -> Optimal d (KPSS Test):     1
  => FINAL DECISION: d=1
Future phase
  StdDev (d=0): 24079.8233
  StdDev (d=1): 3899.6460
  StdDev (d=2): 5897.9319
  -> Optimal d (Variance Rule): 1
  -> Optimal d (KPSS Test):     1
  => FINAL DECISION: d=1

Processing arableland_percent...
Validation phase
  StdDev (d=0): 5.6925
  StdDev (d=1): 1.2745
  StdDev (d=2): 1.7638
  -> Optimal d (Variance Rule): 1
  -> Optimal d (KPSS Test):     1
  => FINAL DECISION: d=1
Future phase
  StdDev (d=0): 6.2357
  StdDev (d=1): 1.1852
  StdDev (d=2): 1.6609
  -> Optimal d (Variance Rule): 1
  -> Optimal d (KPSS Test):     1
  => FINAL DECISION: d=1

Processing arableland_person...
Validation phase
  StdDev (d=0): 0.0371
  StdDev (d=1): 0.0070
  StdDev (d=2): 0.0093
  -> Optimal d (Variance Rule): 1
  -> Optimal d (KPSS Test):     1
  => FINAL DECISION: d=1
Future phase
  StdDev (d=0): 0.0405
  StdDev (d=1): 0.0066
  StdDev (d=2): 0.0089
  -> Optimal d (Variance Rule): 1
  -> Optimal d (KPSS Test):     1
  => FINAL DECISION: d=1

Processing arableland_abs...
Validation phase
  StdDev (d=0): 1642376.8085
  StdDev (d=1): 374573.1842
  StdDev (d=2): 508996.6886
  -> Optimal d (Variance Rule): 1
  -> Optimal d (KPSS Test):     1
  => FINAL DECISION: d=1
Future phase
  StdDev (d=0): 1820035.8043
  StdDev (d=1): 351826.8770
  StdDev (d=2): 492656.4948
  -> Optimal d (Variance Rule): 1
  -> Optimal d (KPSS Test):     1
  => FINAL DECISION: d=1

Processing cerealland_abs...
Validation phase
  StdDev (d=0): 784756.3633
  StdDev (d=1): 194224.9250
  StdDev (d=2): 309991.9987
  -> Optimal d (Variance Rule): 1
  -> Optimal d (KPSS Test):     1
  => FINAL DECISION: d=1
Future phase
  StdDev (d=0): 970679.3614
  StdDev (d=1): 173603.8998
  StdDev (d=2): 284827.7703
  -> Optimal d (Variance Rule): 1
  -> Optimal d (KPSS Test):     1
  => FINAL DECISION: d=1

Processing cropland_percent...
Validation phase
  StdDev (d=0): 0.5724
  StdDev (d=1): 0.2132
  StdDev (d=2): 0.3063
  -> Optimal d (Variance Rule): 1
  -> Optimal d (KPSS Test):     1
  => FINAL DECISION: d=1
Future phase
  StdDev (d=0): 0.8297
  StdDev (d=1): 0.2596
  StdDev (d=2): 0.3556
  -> Optimal d (Variance Rule): 1
  -> Optimal d (KPSS Test):     1
  => FINAL DECISION: d=1

Processing withdrawals_percent...
Validation phase
  StdDev (d=0): 7.0007
  StdDev (d=1): 3.5169
  StdDev (d=2): 5.8021
  -> Optimal d (Variance Rule): 1
  -> Optimal d (KPSS Test):     1
  => FINAL DECISION: d=1
Future phase
  StdDev (d=0): 6.2275
  StdDev (d=1): 3.1561
  StdDev (d=2): 5.1171
  -> Optimal d (Variance Rule): 1
  -> Optimal d (KPSS Test):     1
  => FINAL DECISION: d=1

Processing fertilizer_abs...
Validation phase
  StdDev (d=0): 55.5815
  StdDev (d=1): 17.3567
  StdDev (d=2): 21.8478
  -> Optimal d (Variance Rule): 1
  -> Optimal d (KPSS Test):     2
  => FINAL DECISION: d=1
Future phase
  StdDev (d=0): 53.3439
  StdDev (d=1): 15.7369
  StdDev (d=2): 20.4027
  -> Optimal d (Variance Rule): 1
  -> Optimal d (KPSS Test):     0
  => FINAL DECISION: d=1

Processing fertilizer_percent...
Validation phase
  StdDev (d=0): 134.5223
  StdDev (d=1): 116.1876
  StdDev (d=2): 195.8302
  -> Optimal d (Variance Rule): 1
  -> Optimal d (KPSS Test):     1
  => FINAL DECISION: d=1
Future phase
  StdDev (d=0): 126.1319
  StdDev (d=1): 106.1079
  StdDev (d=2): 176.1407
  -> Optimal d (Variance Rule): 1
  -> Optimal d (KPSS Test):     1
  => FINAL DECISION: d=1

Processing livestock_production_index...
Validation phase
  StdDev (d=0): 15.3042
  StdDev (d=1): 3.0362
  StdDev (d=2): 4.6811
  -> Optimal d (Variance Rule): 1
  -> Optimal d (KPSS Test):     1
  => FINAL DECISION: d=1
Future phase
  StdDev (d=0): 13.9820
  StdDev (d=1): 3.3313
  StdDev (d=2): 5.0586
  -> Optimal d (Variance Rule): 1
  -> Optimal d (KPSS Test):     1
  => FINAL DECISION: d=1

Processing food_production_index...
Validation phase
  StdDev (d=0): 8.9177
  StdDev (d=1): 5.1188
  StdDev (d=2): 8.5055
  -> Optimal d (Variance Rule): 1
  -> Optimal d (KPSS Test):     1
  => FINAL DECISION: d=1
Future phase
  StdDev (d=0): 8.3540
  StdDev (d=1): 4.8151
  StdDev (d=2): 7.8890
  -> Optimal d (Variance Rule): 1
  -> Optimal d (KPSS Test):     1
  => FINAL DECISION: d=1

Processing crop_production_index...
Validation phase
  StdDev (d=0): 7.5177
  StdDev (d=1): 7.4594
  StdDev (d=2): 12.5816
  -> Optimal d (Variance Rule): 1
  -> Optimal d (KPSS Test):     1
  => FINAL DECISION: d=1
Future phase
  StdDev (d=0): 8.5509
  StdDev (d=1): 6.8781
  StdDev (d=2): 11.5154
  -> Optimal d (Variance Rule): 1
  -> Optimal d (KPSS Test):     0
  => FINAL DECISION: d=1

Processing cereal_production...
Validation phase
  StdDev (d=0): 2418760.5658
  StdDev (d=1): 1470630.1193
  StdDev (d=2): 2483860.6252
  -> Optimal d (Variance Rule): 1
  -> Optimal d (KPSS Test):     1
  => FINAL DECISION: d=1
Future phase
  StdDev (d=0): 2251184.9690
  StdDev (d=1): 1407152.4048
  StdDev (d=2): 2410133.4471
  -> Optimal d (Variance Rule): 1
  -> Optimal d (KPSS Test):     1
  => FINAL DECISION: d=1

Processing cerealyield_abs...
Validation phase
  StdDev (d=0): 1023.3142
  StdDev (d=1): 250.8179
  StdDev (d=2): 421.7313
  -> Optimal d (Variance Rule): 1
  -> Optimal d (KPSS Test):     1
  => FINAL DECISION: d=1
Future phase
  StdDev (d=0): 1116.2458
  StdDev (d=1): 278.1733
  StdDev (d=2): 445.6087
  -> Optimal d (Variance Rule): 1
  -> Optimal d (KPSS Test):     1
  => FINAL DECISION: d=1

Processing valueadded_percent...
Validation phase
  StdDev (d=0): 0.5059
  StdDev (d=1): 0.0957
  StdDev (d=2): 0.1399
  -> Optimal d (Variance Rule): 1
  -> Optimal d (KPSS Test):     1
  => FINAL DECISION: d=1
Future phase
  StdDev (d=0): 0.4940
  StdDev (d=1): 0.0972
  StdDev (d=2): 0.1391
  -> Optimal d (Variance Rule): 1
  -> Optimal d (KPSS Test):     1
  => FINAL DECISION: d=1

Processing valueadded_dollars...
Validation phase
  StdDev (d=0): 4327954556.5470
  StdDev (d=1): 3902531788.7777
  StdDev (d=2): 5650526781.0209
  -> Optimal d (Variance Rule): 1
  -> Optimal d (KPSS Test):     0
  => FINAL DECISION: d=1
Future phase
  StdDev (d=0): 4373224509.7849
  StdDev (d=1): 3678699674.6197
  StdDev (d=2): 5170763716.3316
  -> Optimal d (Variance Rule): 1
  -> Optimal d (KPSS Test):     0
  => FINAL DECISION: d=1

Processing exports_percent...
Validation phase
  StdDev (d=0): 0.6006
  StdDev (d=1): 0.1694
  StdDev (d=2): 0.2660
  -> Optimal d (Variance Rule): 1
  -> Optimal d (KPSS Test):     1
  => FINAL DECISION: d=1
Future phase
  StdDev (d=0): 0.5653
  StdDev (d=1): 0.1518
  StdDev (d=2): 0.2366
  -> Optimal d (Variance Rule): 1
  -> Optimal d (KPSS Test):     1
  => FINAL DECISION: d=1

Processing imports_percent...
Validation phase
  StdDev (d=0): 3.7956
  StdDev (d=1): 0.7691
  StdDev (d=2): 1.1474
  -> Optimal d (Variance Rule): 1
  -> Optimal d (KPSS Test):     2
  => FINAL DECISION: d=1
Future phase
  StdDev (d=0): 3.9243
  StdDev (d=1): 0.6913
  StdDev (d=2): 1.0198
  -> Optimal d (Variance Rule): 1
  -> Optimal d (KPSS Test):     1
  => FINAL DECISION: d=1
Configuration successfully saved to: C:\Users\oldan\Desktop\RuralDevelopment\progetto-tirocinio\results\integration_orders.xlsx

## Grid search to find best q
I run the rolling MA forecast on test set's fitting, in order to find q parameter that results in the smallest RMSE. <br>
I save the best q found for each indicator in a dedicated DataFrame i will be able to access in the following cells.

In [6]:
Q_CANDIDATES = [1, 2, 3, 4] 

best_qs = {}
print("STARTING GRID SEARCH")
for col in df.columns:
    if df[col].dropna().empty: continue
    d_train = int(config_df.loc[col]['d_train'])
    
    train, test = pipe.split_train_test(df, col)
    train_serie = train['Value'].dropna()
    test_serie = test['Value'].dropna()
    
    best_q = 1
    best_rmse = float('inf')
    
    for q in Q_CANDIDATES:
        try:
            pred = mod.predict_arima_rolling(
                train_data=train_serie, 
                test_data=test_serie, 
                order=(0, d_train, q),
                refit=True
            )
            metrics = eval.compute_errors(test_serie, pred)
            
            if metrics['RMSE'] < best_rmse:
                best_rmse = metrics['RMSE']
                best_q = q
        except:
            continue
            
    print(f"{col} -> Best q: {best_q} (RMSE: {best_rmse:.4f})")
    best_qs[col] = best_q

STARTING GRID SEARCH
Starting Rolling Forecast ARIMA(0, 2, 1) over 13 steps...
Starting Rolling Forecast ARIMA(0, 2, 2) over 13 steps...
Starting Rolling Forecast ARIMA(0, 2, 3) over 13 steps...
Starting Rolling Forecast ARIMA(0, 2, 4) over 13 steps...
population_percent -> Best q: 1 (RMSE: 0.0344)
Starting Rolling Forecast ARIMA(0, 1, 1) over 13 steps...
Starting Rolling Forecast ARIMA(0, 1, 2) over 13 steps...
Starting Rolling Forecast ARIMA(0, 1, 3) over 13 steps...
Starting Rolling Forecast ARIMA(0, 1, 4) over 13 steps...
population_growth -> Best q: 1 (RMSE: 0.3992)
Starting Rolling Forecast ARIMA(0, 2, 1) over 13 steps...
Starting Rolling Forecast ARIMA(0, 2, 2) over 13 steps...
Starting Rolling Forecast ARIMA(0, 2, 3) over 13 steps...
Starting Rolling Forecast ARIMA(0, 2, 4) over 13 steps...
population_abs -> Best q: 1 (RMSE: 62611.0923)
Starting Rolling Forecast ARIMA(0, 1, 1) over 7 steps...
Starting Rolling Forecast ARIMA(0, 1, 2) over 7 steps...
Starting Rolling Forecast ARIMA(0, 1, 3) over 7 steps...
Starting Rolling Forecast ARIMA(0, 1, 4) over 7 steps...
employment_tot -> Best q: 1 (RMSE: 0.1347)
Starting Rolling Forecast ARIMA(0, 1, 1) over 7 steps...
Starting Rolling Forecast ARIMA(0, 1, 2) over 7 steps...
Starting Rolling Forecast ARIMA(0, 1, 3) over 7 steps...
Starting Rolling Forecast ARIMA(0, 1, 4) over 7 steps...
employment_male -> Best q: 1 (RMSE: 0.1878)
Starting Rolling Forecast ARIMA(0, 1, 1) over 7 steps...
Starting Rolling Forecast ARIMA(0, 1, 2) over 7 steps...
Starting Rolling Forecast ARIMA(0, 1, 3) over 7 steps...
Starting Rolling Forecast ARIMA(0, 1, 4) over 7 steps...
employment_female -> Best q: 2 (RMSE: 0.1152)
Starting Rolling Forecast ARIMA(0, 1, 1) over 7 steps...
Starting Rolling Forecast ARIMA(0, 1, 2) over 7 steps...
Starting Rolling Forecast ARIMA(0, 1, 3) over 7 steps...
Starting Rolling Forecast ARIMA(0, 1, 4) over 7 steps...
forestarea_percent -> Best q: 4 (RMSE: 0.0361)
Starting Rolling Forecast ARIMA(0, 2, 1) over 7 steps...
Starting Rolling Forecast ARIMA(0, 2, 2) over 7 steps...
Starting Rolling Forecast ARIMA(0, 2, 3) over 7 steps...
Starting Rolling Forecast ARIMA(0, 2, 4) over 7 steps...
forestarea_abs -> Best q: 1 (RMSE: 0.0076)
Starting Rolling Forecast ARIMA(0, 1, 1) over 13 steps...
Starting Rolling Forecast ARIMA(0, 1, 2) over 13 steps...
Starting Rolling Forecast ARIMA(0, 1, 3) over 13 steps...
Starting Rolling Forecast ARIMA(0, 1, 4) over 13 steps...
agriland_percent -> Best q: 3 (RMSE: 1.3486)
Starting Rolling Forecast ARIMA(0, 1, 1) over 13 steps...
Starting Rolling Forecast ARIMA(0, 1, 2) over 13 steps...
Starting Rolling Forecast ARIMA(0, 1, 3) over 13 steps...
Starting Rolling Forecast ARIMA(0, 1, 4) over 13 steps...
agriland_abs -> Best q: 1 (RMSE: 3869.7052)
Starting Rolling Forecast ARIMA(0, 1, 1) over 13 steps...
Starting Rolling Forecast ARIMA(0, 1, 2) over 13 steps...
Starting Rolling Forecast ARIMA(0, 1, 3) over 13 steps...
Starting Rolling Forecast ARIMA(0, 1, 4) over 13 steps...
arableland_percent -> Best q: 4 (RMSE: 0.6760)
Starting Rolling Forecast ARIMA(0, 1, 1) over 13 steps...
Starting Rolling Forecast ARIMA(0, 1, 2) over 13 steps...
Starting Rolling Forecast ARIMA(0, 1, 3) over 13 steps...
Starting Rolling Forecast ARIMA(0, 1, 4) over 13 steps...
arableland_person -> Best q: 4 (RMSE: 0.0043)
Starting Rolling Forecast ARIMA(0, 1, 1) over 13 steps...
Starting Rolling Forecast ARIMA(0, 1, 2) over 13 steps...
Starting Rolling Forecast ARIMA(0, 1, 3) over 13 steps...
Starting Rolling Forecast ARIMA(0, 1, 4) over 13 steps...
arableland_abs -> Best q: 1 (RMSE: 243931.5384)
Starting Rolling Forecast ARIMA(0, 1, 1) over 13 steps...
Starting Rolling Forecast ARIMA(0, 1, 2) over 13 steps...
Starting Rolling Forecast ARIMA(0, 1, 3) over 13 steps...
Starting Rolling Forecast ARIMA(0, 1, 4) over 13 steps...
cerealland_abs -> Best q: 1 (RMSE: 59477.5436)
Starting Rolling Forecast ARIMA(0, 1, 1) over 13 steps...
Starting Rolling Forecast ARIMA(0, 1, 2) over 13 steps...
Starting Rolling Forecast ARIMA(0, 1, 3) over 13 steps...
Starting Rolling Forecast ARIMA(0, 1, 4) over 13 steps...
cropland_percent -> Best q: 1 (RMSE: 0.3887)
Starting Rolling Forecast ARIMA(0, 1, 1) over 11 steps...
Starting Rolling Forecast ARIMA(0, 1, 2) over 11 steps...
Starting Rolling Forecast ARIMA(0, 1, 3) over 11 steps...
Starting Rolling Forecast ARIMA(0, 1, 4) over 11 steps...
withdrawals_percent -> Best q: 2 (RMSE: 1.7906)
Starting Rolling Forecast ARIMA(0, 1, 1) over 13 steps...
Starting Rolling Forecast ARIMA(0, 1, 2) over 13 steps...
Starting Rolling Forecast ARIMA(0, 1, 3) over 13 steps...
Starting Rolling Forecast ARIMA(0, 1, 4) over 13 steps...
fertilizer_abs -> Best q: 4 (RMSE: 7.2620)
Starting Rolling Forecast ARIMA(0, 1, 1) over 13 steps...
Starting Rolling Forecast ARIMA(0, 1, 2) over 13 steps...
Starting Rolling Forecast ARIMA(0, 1, 3) over 13 steps...
Starting Rolling Forecast ARIMA(0, 1, 4) over 13 steps...
fertilizer_percent -> Best q: 2 (RMSE: 70.1455)
Starting Rolling Forecast ARIMA(0, 1, 1) over 13 steps...
Starting Rolling Forecast ARIMA(0, 1, 2) over 13 steps...
Starting Rolling Forecast ARIMA(0, 1, 3) over 13 steps...
Starting Rolling Forecast ARIMA(0, 1, 4) over 13 steps...
livestock_production_index -> Best q: 3 (RMSE: 3.8538)
Starting Rolling Forecast ARIMA(0, 1, 1) over 13 steps...
Starting Rolling Forecast ARIMA(0, 1, 2) over 13 steps...
Starting Rolling Forecast ARIMA(0, 1, 3) over 13 steps...
Starting Rolling Forecast ARIMA(0, 1, 4) over 13 steps...
food_production_index -> Best q: 3 (RMSE: 3.5608)
Starting Rolling Forecast ARIMA(0, 1, 1) over 13 steps...
Starting Rolling Forecast ARIMA(0, 1, 2) over 13 steps...
Starting Rolling Forecast ARIMA(0, 1, 3) over 13 steps...
Starting Rolling Forecast ARIMA(0, 1, 4) over 13 steps...
crop_production_index -> Best q: 4 (RMSE: 4.3529)
Starting Rolling Forecast ARIMA(0, 1, 1) over 13 steps...
Starting Rolling Forecast ARIMA(0, 1, 2) over 13 steps...
Starting Rolling Forecast ARIMA(0, 1, 3) over 13 steps...
Starting Rolling Forecast ARIMA(0, 1, 4) over 13 steps...
cereal_production -> Best q: 4 (RMSE: 1058850.3665)
Starting Rolling Forecast ARIMA(0, 1, 1) over 13 steps...
Starting Rolling Forecast ARIMA(0, 1, 2) over 13 steps...
Starting Rolling Forecast ARIMA(0, 1, 3) over 13 steps...
Starting Rolling Forecast ARIMA(0, 1, 4) over 13 steps...
cerealyield_abs -> Best q: 4 (RMSE: 319.0638)
Starting Rolling Forecast ARIMA(0, 1, 1) over 7 steps...
Starting Rolling Forecast ARIMA(0, 1, 2) over 7 steps...
Starting Rolling Forecast ARIMA(0, 1, 3) over 7 steps...
Starting Rolling Forecast ARIMA(0, 1, 4) over 7 steps...
valueadded_percent -> Best q: 4 (RMSE: 0.0749)
Starting Rolling Forecast ARIMA(0, 1, 1) over 7 steps...
Starting Rolling Forecast ARIMA(0, 1, 2) over 7 steps...
Starting Rolling Forecast ARIMA(0, 1, 3) over 7 steps...
Starting Rolling Forecast ARIMA(0, 1, 4) over 7 steps...
valueadded_dollars -> Best q: 1 (RMSE: 2728875994.7772)
Starting Rolling Forecast ARIMA(0, 1, 1) over 13 steps...
Starting Rolling Forecast ARIMA(0, 1, 2) over 13 steps...
Starting Rolling Forecast ARIMA(0, 1, 3) over 13 steps...
Starting Rolling Forecast ARIMA(0, 1, 4) over 13 steps...
exports_percent -> Best q: 1 (RMSE: 0.0389)
Starting Rolling Forecast ARIMA(0, 1, 1) over 13 steps...
Starting Rolling Forecast ARIMA(0, 1, 2) over 13 steps...
Starting Rolling Forecast ARIMA(0, 1, 3) over 13 steps...
Starting Rolling Forecast ARIMA(0, 1, 4) over 13 steps...
imports_percent -> Best q: 3 (RMSE: 0.1151)

## Validation phase on test set
I train a rolling MA model on the train set using (0, d, q) order, where d is the number of best differentiations found on the train set and q is the best q found in the prior cell. I then predict the values of the test set, compute the errors, plot a comparison with the real values and a random walk with drift baseline and i report all of the data i get on the different log files

In [7]:
BASELINE_METHOD = 'drift'

print("VALIDATION PHASE")
for col in df.columns:
    if col not in best_qs: continue
    best_q = best_qs[col]
    d_train = int(config_df.loc[col]['d_train'])
    
    train, test = pipe.split_train_test(df, col)
    train_serie = train['Value'].dropna()
    test_serie = test['Value'].dropna()
    
    start_time = time.time()
    final_pred = mod.predict_arima_rolling(
        train_data=train_serie,
        test_data=test_serie,
        order=(0, d_train, best_q)
    )
    elapsed_time = time.time() - start_time
    
    baseline_pred = mod.get_baseline_prediction(
        BASELINE_METHOD, 
        train_serie, 
        test_serie.index
    )
    
    pred_metrics = eval.compute_errors(test_serie, final_pred)
    pred_residuals = eval.compute_residual_diagnostics(test_serie, final_pred)
    
    print(f"  -> Residuals: Mean={pred_residuals['residual_mean']:.4f}, "
        f"Shapiro P={pred_residuals['shapiro_wilk_pvalue']:.4f}, "
        f"Ljung-Box P={pred_residuals['ljung_box_pvalue']:.4f}")
    
    visual.plot_forecast(
        train=train,
        test=test,
        variable_name=col,
        model_name="MA",
        folder_name="02_MA",
        prediction=final_pred,
        baseline=baseline_pred,
        baseline_name=BASELINE_METHOD,
        rmse=metrics['RMSE'],
        save_plot=True
    )
    
    try:
        lb_p = pred_residuals['ljung_box_pvalue']
        sw_p = pred_residuals['shapiro_wilk_pvalue']
        
        lb_status = "OK" if lb_p > 0.05 else "NO"
        sw_status = "OK" if sw_p > 0.05 else "NO"
        plot_title_suffix = f"\nLjung-Box p={lb_p} ({lb_status}) | Shapiro p={sw_p} ({sw_status})"
        
        visual.plot_residuals(
            y_true=test_serie,
            y_pred=final_pred,
            variable_name=col,
            model_name=f"MA",
            folder_name="02_residMA"
        )
    except Exception as e:
        print(f"Residual plot failed: {e}")
    
    rep.save_experiment_results(
        indicator=col,
        model_name='MA',
        configuration=f'order=(0, {d_train}, {best_q})',
        y_test=test_serie,
        y_pred=final_pred,
        years_test=test_serie.index.year,
        y_train=train_serie,
        params={'p':0, 'd':d_train, 'q':best_q},
        training_time=elapsed_time
    )

VALIDATION PHASE
Starting Rolling Forecast ARIMA(0, 2, 1) over 13 steps...
  -> Residuals: Mean=-0.0108, Shapiro P=0.0000, Ljung-Box P=0.9824
Plot saved: C:\Users\oldan\Desktop\RuralDevelopment\progetto-tirocinio\results\plots\02_MA\MA_population_percent.png
Residuals saved: C:\Users\oldan\Desktop\RuralDevelopment\progetto-tirocinio\results\plots\02_residMA\residMA_population_percent.png
Saving results for MA | population_percent...
Leaderboard updated: population_percent | MA
Save leaderboard complete.
Starting Rolling Forecast ARIMA(0, 1, 1) over 13 steps...
  -> Residuals: Mean=-0.0603, Shapiro P=0.0080, Ljung-Box P=0.1495
Plot saved: C:\Users\oldan\Desktop\RuralDevelopment\progetto-tirocinio\results\plots\02_MA\MA_population_growth.png
Residuals saved: C:\Users\oldan\Desktop\RuralDevelopment\progetto-tirocinio\results\plots\02_residMA\residMA_population_growth.png
Saving results for MA | population_growth...
Leaderboard updated: population_growth | MA
Save leaderboard complete.
Starting Rolling Forecast ARIMA(0, 2, 1) over 13 steps...
  -> Residuals: Mean=-14283.6729, Shapiro P=0.2995, Ljung-Box P=0.4618
Plot saved: C:\Users\oldan\Desktop\RuralDevelopment\progetto-tirocinio\results\plots\02_MA\MA_population_abs.png
Residuals saved: C:\Users\oldan\Desktop\RuralDevelopment\progetto-tirocinio\results\plots\02_residMA\residMA_population_abs.png
Saving results for MA | population_abs...
Leaderboard updated: population_abs | MA
Save leaderboard complete.
Starting Rolling Forecast ARIMA(0, 1, 1) over 7 steps...
  -> Residuals: Mean=-0.0351, Shapiro P=0.2205, Ljung-Box P=0.9734
Plot saved: C:\Users\oldan\Desktop\RuralDevelopment\progetto-tirocinio\results\plots\02_MA\MA_employment_tot.png
Residuals saved: C:\Users\oldan\Desktop\RuralDevelopment\progetto-tirocinio\results\plots\02_residMA\residMA_employment_tot.png
Saving results for MA | employment_tot...
Leaderboard updated: employment_tot | MA
Save leaderboard complete.
Starting Rolling Forecast ARIMA(0, 1, 1) over 7 steps...
  -> Residuals: Mean=-0.0314, Shapiro P=0.5088, Ljung-Box P=0.5965
Plot saved: C:\Users\oldan\Desktop\RuralDevelopment\progetto-tirocinio\results\plots\02_MA\MA_employment_male.png
Residuals saved: C:\Users\oldan\Desktop\RuralDevelopment\progetto-tirocinio\results\plots\02_residMA\residMA_employment_male.png
Saving results for MA | employment_male...
Leaderboard updated: employment_male | MA
Save leaderboard complete.
Starting Rolling Forecast ARIMA(0, 1, 2) over 7 steps...
  -> Residuals: Mean=-0.0407, Shapiro P=0.8215, Ljung-Box P=0.3487
Plot saved: C:\Users\oldan\Desktop\RuralDevelopment\progetto-tirocinio\results\plots\02_MA\MA_employment_female.png
Residuals saved: C:\Users\oldan\Desktop\RuralDevelopment\progetto-tirocinio\results\plots\02_residMA\residMA_employment_female.png
Saving results for MA | employment_female...
Leaderboard updated: employment_female | MA
Save leaderboard complete.
Starting Rolling Forecast ARIMA(0, 1, 4) over 7 steps...
  -> Residuals: Mean=0.0346, Shapiro P=0.5042, Ljung-Box P=0.7992
Plot saved: C:\Users\oldan\Desktop\RuralDevelopment\progetto-tirocinio\results\plots\02_MA\MA_forestarea_percent.png
Residuals saved: C:\Users\oldan\Desktop\RuralDevelopment\progetto-tirocinio\results\plots\02_residMA\residMA_forestarea_percent.png
Saving results for MA | forestarea_percent...
Leaderboard updated: forestarea_percent | MA
Save leaderboard complete.
Starting Rolling Forecast ARIMA(0, 2, 1) over 7 steps...
  -> Residuals: Mean=0.0029, Shapiro P=0.0000, Ljung-Box P=0.9385
Plot saved: C:\Users\oldan\Desktop\RuralDevelopment\progetto-tirocinio\results\plots\02_MA\MA_forestarea_abs.png
Residuals saved: C:\Users\oldan\Desktop\RuralDevelopment\progetto-tirocinio\results\plots\02_residMA\residMA_forestarea_abs.png
Saving results for MA | forestarea_abs...
Leaderboard updated: forestarea_abs | MA
Save leaderboard complete.
Starting Rolling Forecast ARIMA(0, 1, 3) over 13 steps...
  -> Residuals: Mean=-0.1988, Shapiro P=0.2363, Ljung-Box P=0.2127
Plot saved: C:\Users\oldan\Desktop\RuralDevelopment\progetto-tirocinio\results\plots\02_MA\MA_agriland_percent.png
Residuals saved: C:\Users\oldan\Desktop\RuralDevelopment\progetto-tirocinio\results\plots\02_residMA\residMA_agriland_percent.png
Saving results for MA | agriland_percent...
Leaderboard updated: agriland_percent | MA
Save leaderboard complete.
Starting Rolling Forecast ARIMA(0, 1, 1) over 13 steps...
  -> Residuals: Mean=-1580.7469, Shapiro P=0.0870, Ljung-Box P=0.0277
Plot saved: C:\Users\oldan\Desktop\RuralDevelopment\progetto-tirocinio\results\plots\02_MA\MA_agriland_abs.png
Residuals saved: C:\Users\oldan\Desktop\RuralDevelopment\progetto-tirocinio\results\plots\02_residMA\residMA_agriland_abs.png
Saving results for MA | agriland_abs...
Leaderboard updated: agriland_abs | MA
Save leaderboard complete.
Starting Rolling Forecast ARIMA(0, 1, 4) over 13 steps...
  -> Residuals: Mean=0.0410, Shapiro P=0.9573, Ljung-Box P=0.2997
Plot saved: C:\Users\oldan\Desktop\RuralDevelopment\progetto-tirocinio\results\plots\02_MA\MA_arableland_percent.png
Residuals saved: C:\Users\oldan\Desktop\RuralDevelopment\progetto-tirocinio\results\plots\02_residMA\residMA_arableland_percent.png
Saving results for MA | arableland_percent...
Leaderboard updated: arableland_percent | MA
Save leaderboard complete.
Starting Rolling Forecast ARIMA(0, 1, 4) over 13 steps...
  -> Residuals: Mean=-0.0002, Shapiro P=0.9520, Ljung-Box P=0.2540
Plot saved: C:\Users\oldan\Desktop\RuralDevelopment\progetto-tirocinio\results\plots\02_MA\MA_arableland_person.png
Residuals saved: C:\Users\oldan\Desktop\RuralDevelopment\progetto-tirocinio\results\plots\02_residMA\residMA_arableland_person.png
Saving results for MA | arableland_person...
Leaderboard updated: arableland_person | MA
Save leaderboard complete.
Starting Rolling Forecast ARIMA(0, 1, 1) over 13 steps...
  -> Residuals: Mean=-23478.0031, Shapiro P=0.9877, Ljung-Box P=0.1902
Plot saved: C:\Users\oldan\Desktop\RuralDevelopment\progetto-tirocinio\results\plots\02_MA\MA_arableland_abs.png
Residuals saved: C:\Users\oldan\Desktop\RuralDevelopment\progetto-tirocinio\results\plots\02_residMA\residMA_arableland_abs.png
Saving results for MA | arableland_abs...
Leaderboard updated: arableland_abs | MA
Save leaderboard complete.
Starting Rolling Forecast ARIMA(0, 1, 1) over 13 steps...
  -> Residuals: Mean=-35736.8274, Shapiro P=0.6610, Ljung-Box P=0.8205
Plot saved: C:\Users\oldan\Desktop\RuralDevelopment\progetto-tirocinio\results\plots\02_MA\MA_cerealland_abs.png
Residuals saved: C:\Users\oldan\Desktop\RuralDevelopment\progetto-tirocinio\results\plots\02_residMA\residMA_cerealland_abs.png
Saving results for MA | cerealland_abs...
Leaderboard updated: cerealland_abs | MA
Save leaderboard complete.
Starting Rolling Forecast ARIMA(0, 1, 1) over 13 steps...
  -> Residuals: Mean=-0.0450, Shapiro P=0.8820, Ljung-Box P=0.4198
Plot saved: C:\Users\oldan\Desktop\RuralDevelopment\progetto-tirocinio\results\plots\02_MA\MA_cropland_percent.png
Residuals saved: C:\Users\oldan\Desktop\RuralDevelopment\progetto-tirocinio\results\plots\02_residMA\residMA_cropland_percent.png
Saving results for MA | cropland_percent...
Leaderboard updated: cropland_percent | MA
Save leaderboard complete.
Starting Rolling Forecast ARIMA(0, 1, 2) over 11 steps...
  -> Residuals: Mean=0.9835, Shapiro P=0.0004, Ljung-Box P=0.0407
Plot saved: C:\Users\oldan\Desktop\RuralDevelopment\progetto-tirocinio\results\plots\02_MA\MA_withdrawals_percent.png
Residuals saved: C:\Users\oldan\Desktop\RuralDevelopment\progetto-tirocinio\results\plots\02_residMA\residMA_withdrawals_percent.png
Saving results for MA | withdrawals_percent...
Leaderboard updated: withdrawals_percent | MA
Save leaderboard complete.
Starting Rolling Forecast ARIMA(0, 1, 4) over 13 steps...
  -> Residuals: Mean=-1.0847, Shapiro P=0.4998, Ljung-Box P=0.0299
Plot saved: C:\Users\oldan\Desktop\RuralDevelopment\progetto-tirocinio\results\plots\02_MA\MA_fertilizer_abs.png
Residuals saved: C:\Users\oldan\Desktop\RuralDevelopment\progetto-tirocinio\results\plots\02_residMA\residMA_fertilizer_abs.png
Saving results for MA | fertilizer_abs...
Leaderboard updated: fertilizer_abs | MA
Save leaderboard complete.
Starting Rolling Forecast ARIMA(0, 1, 2) over 13 steps...
  -> Residuals: Mean=-53.5688, Shapiro P=0.7997, Ljung-Box P=0.1175
Plot saved: C:\Users\oldan\Desktop\RuralDevelopment\progetto-tirocinio\results\plots\02_MA\MA_fertilizer_percent.png
Residuals saved: C:\Users\oldan\Desktop\RuralDevelopment\progetto-tirocinio\results\plots\02_residMA\residMA_fertilizer_percent.png
Saving results for MA | fertilizer_percent...
Leaderboard updated: fertilizer_percent | MA
Save leaderboard complete.
Starting Rolling Forecast ARIMA(0, 1, 3) over 13 steps...
  -> Residuals: Mean=-0.8362, Shapiro P=0.7743, Ljung-Box P=0.9330
Plot saved: C:\Users\oldan\Desktop\RuralDevelopment\progetto-tirocinio\results\plots\02_MA\MA_livestock_production_index.png
Residuals saved: C:\Users\oldan\Desktop\RuralDevelopment\progetto-tirocinio\results\plots\02_residMA\residMA_livestock_production_index.png
Saving results for MA | livestock_production_index...
Leaderboard updated: livestock_production_index | MA
Save leaderboard complete.
Starting Rolling Forecast ARIMA(0, 1, 3) over 13 steps...
  -> Residuals: Mean=-1.8558, Shapiro P=0.9965, Ljung-Box P=0.9478
Plot saved: C:\Users\oldan\Desktop\RuralDevelopment\progetto-tirocinio\results\plots\02_MA\MA_food_production_index.png
Residuals saved: C:\Users\oldan\Desktop\RuralDevelopment\progetto-tirocinio\results\plots\02_residMA\residMA_food_production_index.png
Saving results for MA | food_production_index...
Leaderboard updated: food_production_index | MA
Save leaderboard complete.
Starting Rolling Forecast ARIMA(0, 1, 4) over 13 steps...
  -> Residuals: Mean=-2.0177, Shapiro P=0.9303, Ljung-Box P=0.4136
Plot saved: C:\Users\oldan\Desktop\RuralDevelopment\progetto-tirocinio\results\plots\02_MA\MA_crop_production_index.png
Residuals saved: C:\Users\oldan\Desktop\RuralDevelopment\progetto-tirocinio\results\plots\02_residMA\residMA_crop_production_index.png
Saving results for MA | crop_production_index...
Leaderboard updated: crop_production_index | MA
Save leaderboard complete.
Starting Rolling Forecast ARIMA(0, 1, 4) over 13 steps...
  -> Residuals: Mean=-297971.8949, Shapiro P=0.1713, Ljung-Box P=0.5212
Plot saved: C:\Users\oldan\Desktop\RuralDevelopment\progetto-tirocinio\results\plots\02_MA\MA_cereal_production.png
Residuals saved: C:\Users\oldan\Desktop\RuralDevelopment\progetto-tirocinio\results\plots\02_residMA\residMA_cereal_production.png
Saving results for MA | cereal_production...
Leaderboard updated: cereal_production | MA
Save leaderboard complete.
Starting Rolling Forecast ARIMA(0, 1, 4) over 13 steps...
  -> Residuals: Mean=-6.5231, Shapiro P=0.5808, Ljung-Box P=0.5712
Plot saved: C:\Users\oldan\Desktop\RuralDevelopment\progetto-tirocinio\results\plots\02_MA\MA_cerealyield_abs.png
Residuals saved: C:\Users\oldan\Desktop\RuralDevelopment\progetto-tirocinio\results\plots\02_residMA\residMA_cerealyield_abs.png
Saving results for MA | cerealyield_abs...
Leaderboard updated: cerealyield_abs | MA
Save leaderboard complete.
Starting Rolling Forecast ARIMA(0, 1, 4) over 7 steps...
  -> Residuals: Mean=0.0288, Shapiro P=0.4014, Ljung-Box P=0.1783
Plot saved: C:\Users\oldan\Desktop\RuralDevelopment\progetto-tirocinio\results\plots\02_MA\MA_valueadded_percent.png
Residuals saved: C:\Users\oldan\Desktop\RuralDevelopment\progetto-tirocinio\results\plots\02_residMA\residMA_valueadded_percent.png
Saving results for MA | valueadded_percent...
Leaderboard updated: valueadded_percent | MA
Save leaderboard complete.
Starting Rolling Forecast ARIMA(0, 1, 1) over 7 steps...
  -> Residuals: Mean=1468626389.9540, Shapiro P=0.8995, Ljung-Box P=0.8527
Plot saved: C:\Users\oldan\Desktop\RuralDevelopment\progetto-tirocinio\results\plots\02_MA\MA_valueadded_dollars.png
Residuals saved: C:\Users\oldan\Desktop\RuralDevelopment\progetto-tirocinio\results\plots\02_residMA\residMA_valueadded_dollars.png
Saving results for MA | valueadded_dollars...
Leaderboard updated: valueadded_dollars | MA
Save leaderboard complete.
Starting Rolling Forecast ARIMA(0, 1, 1) over 13 steps...
  -> Residuals: Mean=-0.0070, Shapiro P=0.9897, Ljung-Box P=0.0961
Plot saved: C:\Users\oldan\Desktop\RuralDevelopment\progetto-tirocinio\results\plots\02_MA\MA_exports_percent.png
Residuals saved: C:\Users\oldan\Desktop\RuralDevelopment\progetto-tirocinio\results\plots\02_residMA\residMA_exports_percent.png
Saving results for MA | exports_percent...
Leaderboard updated: exports_percent | MA
Save leaderboard complete.
Starting Rolling Forecast ARIMA(0, 1, 3) over 13 steps...
  -> Residuals: Mean=-0.0445, Shapiro P=0.9736, Ljung-Box P=0.8288
Plot saved: C:\Users\oldan\Desktop\RuralDevelopment\progetto-tirocinio\results\plots\02_MA\MA_imports_percent.png
Residuals saved: C:\Users\oldan\Desktop\RuralDevelopment\progetto-tirocinio\results\plots\02_residMA\residMA_imports_percent.png
Saving results for MA | imports_percent...
Leaderboard updated: imports_percent | MA
Save leaderboard complete.

## Future forecasts

In [8]:
TARGET_YEAR = 2030
BASELINE_METHOD = 'drift'

print(f"Future forecasting (up to {TARGET_YEAR}) ---")
for col in df.columns:
    if col not in best_qs: continue
    
    best_q = best_qs[col]
    d_full = int(config_df.loc[col]['d_full'])
    
    full_series = df[col].dropna()
    
    last_date = full_series.index[-1]
    if last_date.year >= TARGET_YEAR:
        print(f"  -> Data already available until {last_date.year}. Skipping.")
        continue
    future_index = pd.date_range(
        start=last_date + pd.DateOffset(years=1),
        end=pd.Timestamp(f"{TARGET_YEAR}-01-01"),
        freq='YS'
    )
    
    start_time = time.time()
    future_pred = mod.predict_arima_family(
        train_data=full_series,
        forecast_index=future_index,
        order=(0, d_full, best_q)
    )
    elapsed_time = time.time() - start_time
    future_df = future_pred.to_frame(name='pred')
    future_df['year'] = future_df.index.year
    future_df.reset_index(drop=True, inplace=True)
    
    baseline_pred = mod.get_baseline_prediction(
        method_name=BASELINE_METHOD, 
        train_data=full_series,
        forecast_index=future_index
    )
    baseline_df = baseline_pred.to_frame(name='pred')
    baseline_df['year'] = baseline_df.index.year
    baseline_df.reset_index(drop=True, inplace=True)
    
    visual.plot_future_forecasts(
        full_history=full_series,
        future_pred=future_df,
        baseline_pred=baseline_df,
        variable_name=col,
        model_name='MA',
        baseline_name=BASELINE_METHOD,
        folder_name='02_futureMA',
        save_plots=True
    )

Future forecasting (up to 2030) ---
Future Plot saved: C:\Users\oldan\Desktop\RuralDevelopment\progetto-tirocinio\results\plots\02_futureMA\futureMA_population_percent.png
Future Plot saved: C:\Users\oldan\Desktop\RuralDevelopment\progetto-tirocinio\results\plots\02_futureMA\futureMA_population_growth.png
Future Plot saved: C:\Users\oldan\Desktop\RuralDevelopment\progetto-tirocinio\results\plots\02_futureMA\futureMA_population_abs.png
Future Plot saved: C:\Users\oldan\Desktop\RuralDevelopment\progetto-tirocinio\results\plots\02_futureMA\futureMA_employment_tot.png
Future Plot saved: C:\Users\oldan\Desktop\RuralDevelopment\progetto-tirocinio\results\plots\02_futureMA\futureMA_employment_male.png
Future Plot saved: C:\Users\oldan\Desktop\RuralDevelopment\progetto-tirocinio\results\plots\02_futureMA\futureMA_employment_female.png
Future Plot saved: C:\Users\oldan\Desktop\RuralDevelopment\progetto-tirocinio\results\plots\02_futureMA\futureMA_forestarea_percent.png
Future Plot saved: C:\Users\oldan\Desktop\RuralDevelopment\progetto-tirocinio\results\plots\02_futureMA\futureMA_forestarea_abs.png
Future Plot saved: C:\Users\oldan\Desktop\RuralDevelopment\progetto-tirocinio\results\plots\02_futureMA\futureMA_agriland_percent.png
Future Plot saved: C:\Users\oldan\Desktop\RuralDevelopment\progetto-tirocinio\results\plots\02_futureMA\futureMA_agriland_abs.png
Future Plot saved: C:\Users\oldan\Desktop\RuralDevelopment\progetto-tirocinio\results\plots\02_futureMA\futureMA_arableland_percent.png
Future Plot saved: C:\Users\oldan\Desktop\RuralDevelopment\progetto-tirocinio\results\plots\02_futureMA\futureMA_arableland_person.png
Future Plot saved: C:\Users\oldan\Desktop\RuralDevelopment\progetto-tirocinio\results\plots\02_futureMA\futureMA_arableland_abs.png
Future Plot saved: C:\Users\oldan\Desktop\RuralDevelopment\progetto-tirocinio\results\plots\02_futureMA\futureMA_cerealland_abs.png
Future Plot saved: C:\Users\oldan\Desktop\RuralDevelopment\progetto-tirocinio\results\plots\02_futureMA\futureMA_cropland_percent.png
Future Plot saved: C:\Users\oldan\Desktop\RuralDevelopment\progetto-tirocinio\results\plots\02_futureMA\futureMA_withdrawals_percent.png
Future Plot saved: C:\Users\oldan\Desktop\RuralDevelopment\progetto-tirocinio\results\plots\02_futureMA\futureMA_fertilizer_abs.png
Future Plot saved: C:\Users\oldan\Desktop\RuralDevelopment\progetto-tirocinio\results\plots\02_futureMA\futureMA_fertilizer_percent.png
Future Plot saved: C:\Users\oldan\Desktop\RuralDevelopment\progetto-tirocinio\results\plots\02_futureMA\futureMA_livestock_production_index.png
Future Plot saved: C:\Users\oldan\Desktop\RuralDevelopment\progetto-tirocinio\results\plots\02_futureMA\futureMA_food_production_index.png
Future Plot saved: C:\Users\oldan\Desktop\RuralDevelopment\progetto-tirocinio\results\plots\02_futureMA\futureMA_crop_production_index.png
Future Plot saved: C:\Users\oldan\Desktop\RuralDevelopment\progetto-tirocinio\results\plots\02_futureMA\futureMA_cereal_production.png
Future Plot saved: C:\Users\oldan\Desktop\RuralDevelopment\progetto-tirocinio\results\plots\02_futureMA\futureMA_cerealyield_abs.png
Future Plot saved: C:\Users\oldan\Desktop\RuralDevelopment\progetto-tirocinio\results\plots\02_futureMA\futureMA_valueadded_percent.png
Future Plot saved: C:\Users\oldan\Desktop\RuralDevelopment\progetto-tirocinio\results\plots\02_futureMA\futureMA_valueadded_dollars.png
Future Plot saved: C:\Users\oldan\Desktop\RuralDevelopment\progetto-tirocinio\results\plots\02_futureMA\futureMA_exports_percent.png
Future Plot saved: C:\Users\oldan\Desktop\RuralDevelopment\progetto-tirocinio\results\plots\02_futureMA\futureMA_imports_percent.png

==================================================================================

<a class="anchor" id="autocorrelation"> </a>
## <a id='toc1_6_'></a>[Check autocorrelation](#toc0_)

suitable indicators are the one that:
- in the ACF plot --> shows cut-off behaviour: significant coefficients up until lag q, then abruptly becomes non significant.
- in the PACF plot --> decrease gradually <br>
q will become the order of our MA(q) model

[Box-jenkins](https://openforecast.org/adam/BJApproach.html) <br>
For an MA(q) process, ACF will drop abruptly right after the lag q; <br>
For an MA(q) process, PACF will decline either exponentially or alternatingly (based on the specific values of parameters), starting from the lag q. <br>
However, these rules are not necessarily bi-directional and might not work in practice, e.g. if we deal with MA(q), ACF drops abruptly right after the lag q, but if ACF drops abruptly after the lag q, then this does not necessarily mean that we deal with MA(q). The former follows directly from the assumed “true” model, while the latter refers to the identification of the model on the data, and there can be different reasons for the ACF to behave in the way it does.

L'ispezione visiva mostra un taglio netto in entrambi i grafici, suggerendo un processo a memoria breve o parametri deboli. Nessuna time serie è perfettamente adatta a MA ma provo a farla andare su time serie che mostrano ACF abruptly decreasing

In [10]:
SUITABLE = ["Rural population growth (annual %)",
"Rural population",
"Agriculture, forestry, and fishing, value added (% of GDP)",
"Agriculture, forestry, and fishing, value added (current US$)",
"Annual freshwater withdrawals, agriculture (% of total freshwater withdrawal)",
"Cereal yield (kg per hectare)",
"Livestock production index (2014-2016 = 100)",
"Food production index (2014-2016 = 100)",
"Crop production index (2014-2016 = 100)",
"Cereal production (metric tons)",
"Permanent cropland (% of land area)",
"Land under cereal production (hectares)",
"Arable land (% of land area)",
"Arable land (hectares per person)",
"Arable land (hectares)",
"Agricultural land (% of land area)",
"Agricultural land (sq. km)",
"Fertilizer consumption (kilograms per hectare of arable land)",
"Fertilizer consumption (% of fertilizer production)"
]

In [ ]:
# def rolling_forecast(df: pd.DataFrame, train_len: int, horizon: int, window: int, method: str) -> list:
#     total_len = train_len + horizon

#     if method == 'mean':
#         pred_mean = []
#         for i in range(train_len, total_len, window):
#             mean = np.mean(df["Diff"][:i])
#             pred_mean.extend([mean] * window)
#         return pred_mean

#     elif method == 'last':
#         pred_last_value = []
#         for i in range(train_len, total_len, window):
#             last_value = df["Diff"][:i].iloc[-1]
#             pred_last_value.extend([last_value] * window)
#         return pred_last_value

#     elif method == 'MA':
#         pred_MA = []
#         for i in range(train_len, total_len, window):
#             if len(df["Diff"][:i]) < 12:
#                 pred_MA.extend([np.nan] * window)
#                 continue
#             try:
#                 model = SARIMAX(df["Diff"][:i].values, order=(0,0,1))
#                 res = model.fit(disp=False)
#                 predictions = res.get_prediction(start=i, end=i + window - 1)
#                 oos_pred = predictions.predicted_mean
#                 pred_MA.extend(oos_pred)
#             except Exception as e:
#                 print(f"Errore AR per finestra {i}: {e}")
#                 pred_MA.extend([np.nan] * window)
#         return pred_MA

In [ ]:
# # ROLLING FORECAST TO MODEL MOVING AVERAGE
# from statsmodels.tsa.statespace.sarimax import SARIMAX

# def rolling_forecast(df: pd.DataFrame, train_len: int, horizon: int, window: int, method: str) -> list:
#     total_len = train_len + horizon
#     if method == 'mean':
#         pred_mean = []
#         for i in range(train_len, total_len, window):
#             mean = np.mean(df[:i])
#             pred_mean.extend(mean for _ in range(window))
#         return pred_mean

#     elif method == 'last':
#         pred_last_value = []
#         for i in range(train_len, total_len, window):
#             last_value = df[:i].iloc[-1]
#             pred_last_value.extend(last_value for _ in range(window))
#         return pred_last_value
    
#     elif method == 'MA':
#         pred_MA = []
#         for i in range(train_len, total_len, window):
#             model = SARIMAX(df[:i], order=(0,0,2))
#             res = model.fit(disp=False)
#             predictions = res.get_prediction(0, i + window - 1)
#             oos_pred = predictions.predicted_mean.iloc[-window:]
#             pred_MA.extend(oos_pred)
#         return pred_MA
# pred_df = test.copy()

# TRAIN_LEN = len(train)
# HORIZON = len(test)
# WINDOW = 1

# pred_mean = rolling_forecast(df_livestock['Diff'], TRAIN_LEN, HORIZON, WINDOW, 'mean')
# pred_last_value = rolling_forecast(df_livestock['Diff'], TRAIN_LEN, HORIZON, WINDOW, 'last')
# pred_MA = rolling_forecast(df_livestock['Diff'], TRAIN_LEN, HORIZON, WINDOW, 'MA')

# pred_df['pred_mean'] = pred_mean
# pred_df['pred_last_value'] = pred_last_value
# pred_df['pred_MA'] = pred_MA

# pred_df.head()

    Year   Value  Diff  pred_mean  pred_last_value   pred_MA
55  2016  102.47  0.96   0.566667             5.49  0.503091
56  2017  100.09 -2.38   0.573818             0.96 -0.494642
57  2018  106.33  6.24   0.521071            -2.38  0.063690
58  2019  107.13  0.80   0.621404             6.24 -0.219083
59  2020  104.73 -2.40   0.624483             0.80 -0.785769